#!/bin/bash

key=$(cat key)

#curl -s "http://api.wunderground.com/api/$key/hourly/q/autoip.json" > .currentForecast/hourly_forecast
curl -s "http://api.wunderground.com/api/$key/hourly/q/zmw:00000.80.10727.json.json" > .currentForecast/hourly_forecast
#curl -s "http://api.wunderground.com/api/$key/conditions/q/autoip.json" > .currentForecast/current_condition
curl -s "http://api.wunderground.com/api/$key/conditions/q/zmw:00000.80.10727.json" > .currentForecast/current_condition
